## <center>**MARIADB Databases : Implementation and Querying (With Indexing)**</center>
This notebook contains the code to establish the databases in Mariadb and to perform the required queries and note their times.

According to my roll number, the csv files I picked for creating these databases were :
- A-100
- A-1000
- A-10000
- B-100-3-1
- B-100-5-2
- B-100-10-1
- B-1000-5-2
- B-1000-10-4
- B-1000-50-2
- B-10000-5-1
- B-10000-50-2
- B-10000-500-1


The 9 databases formed according to question were therefore:
- **A_100, B_100_3_1 (db1)**
- **A_100, B_100_5_2 (db2)**
- **A_100, B_100_10_1 (db3)**
- **A_1000, B_1000_5_2 (db4)**
- **A_1000, B_1000_10_4 (db5)**
- **A_1000, B_1000_50_2 (db6)**
- **A_10000, B_10000_5_1 (db7)**
- **A_10000, B_10000_50-2 (db8)**
- **A-10000, B_10000_500_1 (db9)**



We start off by importing the required packages. <br>
**NOTE:** You will have to first install the packages by uncommenting the lines below if they are not already installed on your system.

In [1]:
#!pip3 install mariadb
import mariadb
import pandas as pd
from mariadb import Error
from time import time
import numpy as np
import csv

#### **Function to create a database**
This function creates a connection to the specified database and if it doesn't already exist, it creates that database.<br>
**NOTE:** This will cerate the database in the same directory as the notebook. IF you want a different path, specify it while passing the argument to the create_database function. Also change the username and password as per requirement

In [2]:
def create_connection1():
    
    connection = None
    try:
        connection = mariadb.connect(user="user1",
        password= "password1")
        c = connection.cursor()
        c.execute('DROP DATABASE if EXISTS db1;')
        c.execute('CREATE DATABASE db1;')
        #print(db)
    except Error as e:
        print(e)
    finally:
        if connection :
            connection.close()
            
            
def create_connection2():
    
    connection = None
    try:
        connection = mariadb.connect(user="user1",
        password= "password1")
        c = connection.cursor()
        c.execute('DROP DATABASE if EXISTS db2;')
        c.execute('CREATE DATABASE db2;')
        #print(db)
    except Error as e:
        print(e)
    finally:
        if connection :
            connection.close()
            
def create_connection3():
    
    connection = None
    try:
        connection = mariadb.connect(user="user1",
        password= "password1")
        c = connection.cursor()
        c.execute('DROP DATABASE if EXISTS db3;')
        c.execute('CREATE DATABASE db3;')
        #print(db)
    except Error as e:
        print(e)
    finally:
        if connection :
            connection.close()
            
def create_connection4():
    
    connection = None
    try:
        connection = mariadb.connect(user="user1",
        password= "password1")
        c = connection.cursor()
        c.execute('DROP DATABASE if EXISTS db4;')
        c.execute('CREATE DATABASE db4;')
        #print(db)
    except Error as e:
        print(e)
    finally:
        if connection :
            connection.close()
            
def create_connection5():
    
    connection = None
    try:
        connection = mariadb.connect(user="user1",
        password= "password1")
        c = connection.cursor()
        c.execute('DROP DATABASE if EXISTS db5;')
        c.execute('CREATE DATABASE db5;')
        #print(db)
    except Error as e:
        print(e)
    finally:
        if connection :
            connection.close()
            
def create_connection6():
    
    connection = None
    try:
        connection = mariadb.connect(user="user1",
        password= "password1")
        c = connection.cursor()
        c.execute('DROP DATABASE if EXISTS db6;')
        c.execute('CREATE DATABASE db6;')
        #print(db)
    except Error as e:
        print(e)
    finally:
        if connection :
            connection.close()
            
def create_connection7():
    
    connection = None
    try:
        connection = mariadb.connect(user="user1",
        password= "password1")
        c = connection.cursor()
        c.execute('DROP DATABASE if EXISTS db7;')
        c.execute('CREATE DATABASE db7;')
        #print(db)
    except Error as e:
        print(e)
    finally:
        if connection :
            connection.close()
            
def create_connection8():
    
    connection = None
    try:
        connection = mariadb.connect(user="user1",
        password= "password1")
        c = connection.cursor()
        c.execute('DROP DATABASE if EXISTS db8;')
        c.execute('CREATE DATABASE db8;')
        #print(db)
    except Error as e:
        print(e)
    finally:
        if connection :
            connection.close()
            
def create_connection9():
    
    connection = None
    try:
        connection = mariadb.connect(user="user1",
        password= "password1")
        c = connection.cursor()
        c.execute('DROP DATABASE if EXISTS db9;')
        c.execute('CREATE DATABASE db9;')
        #print(db)
    except Error as e:
        print(e)
    finally:
        if connection :
            connection.close()
            

In [3]:
create_connection('db1')
create_connection("db2")
create_connection("db3")
create_connection("db4")
create_connection("db5")
create_connection("db6")
create_connection("db7")
create_connection("db8")
create_connection("db9")

db1
db2
db3
db4
db5
db6
db7
db8
db9


### <center>**Creating database tables and Importing data in db**</center>
#### **Function to create tables in database**
After creating the databases, next we create the tables inside the database and import data into those tables. Below is the function for that which takes as argument the database, and the two tables you want to import in that database .i.e. A and B. <br>
**NOTE:** Please take care while of the path while passing arguments to this function. While running, I had the csv files in the exact same directory. Mention the path correctly in case there is a different path. And take care of the username and password fields.

In [4]:
def create_tables(db, table1, table2):
    
    connection = mariadb.connect(user="user1",
    password= "password1",
    database= db)

    c = connection.cursor()
    
    c.execute('DROP TABLE if EXISTS B')
    c.execute('DROP TABLE if Exists A')

    c.execute('''CREATE TABLE A( A1 int,
                A2 text );''')

    c.execute('CREATE TABLE B( B1 int, B2 int, B3 varchar(255))')

    connection.commit()
    
    with open(table1, newline = '') as csvfile:
        reader = csv.reader(csvfile, delimiter=',')
        next(reader)
        for row in reader:
            A1 = int(row[0])
            A2 = row[1]
            c.execute(f'INSERT INTO A(A1, A2) VALUES("{A1}", "{A2}");')
    
    with open(table2, newline = '') as csvfile:
        reader = csv.reader(csvfile, delimiter=',')
        next(reader)
        for row in reader:
            B1 = int(row[0])
            B2 = int(row[1])
            B3 = row[2]
            c.execute(f'INSERT INTO B(B1, B2, B3) VALUES("{B1}", "{B2}", "{B3}");')
    
    connection.commit()
    connection.close()

#### **Database 1 - db1.db**

In [5]:
create_tables('db1', 'A-100.csv', 'B-100-3-1.csv')

#### **Database 2 - db2.db**

In [6]:
create_tables('db2', r'A-100.csv', r'B-100-5-2.csv')

#### **Database 3 - db3.db**

In [7]:
create_tables('db3', r'A-100.csv', r'B-100-10-1.csv')

#### **Database 4 - db4.db**

In [8]:
create_tables('db4', r'A-1000.csv', r'B-1000-5-2.csv')

#### **Database 5 - db5.db**

In [9]:
create_tables('db5', r'A-1000.csv', r'B-1000-10-4.csv')

#### **Database 6 - db6.db**

In [10]:
create_tables('db6', r'A-1000.csv', r'B-1000-50-2.csv')

#### **Database 7 - db7.db**

In [11]:
create_tables('db7', r'A-10000.csv', r'B-10000-5-1.csv')

#### **Database 8 - db8.db**

In [12]:
create_tables('db8', r'A-10000.csv', r'B-10000-50-2.csv')

#### **Database 9 - db9.db**

In [13]:
create_tables('db9', r'A-10000.csv', r'B-10000-500-1.csv')

### <center>**Querying the databases and finding time**</center>
#### **Function to run a query and report time**
This function loops 7 times and creates connection to each of the 9 databases one by one to execute the query passed on to it. 
*Since while executing on shell directly executes and then prints the query, so to counter the overhead the same thing has been followed while noting time.*

In [14]:
def run_query(query):
    
    t = [[0] * 9] * 7
    for i in range(7):
        connection = mariadb.connect(user="user1", password= "password1", database = 'db1')
        c = connection.cursor()
        tic = time()
        c.execute(query)
        #print(pd.DataFrame(c.fetchall()))
        x = c.fetchall()
        toc = time()
        print(toc - tic)
        t[i][0] = toc - tic
        connection.close()
        
        connection = mariadb.connect(user="user1", password= "password1", database = 'db2')
        c = connection.cursor()
        tic = time()
        c.execute(query)
        #print(pd.DataFrame(c.fetchall()))
        x = c.fetchall()
        toc = time()
        print(toc - tic)
        t[i][1] = toc - tic        
        connection.close()
        
        connection = mariadb.connect(user="user1", password= "password1", database = 'db3')
        c = connection.cursor()
        tic = time()
        c.execute(query)
        #print(pd.DataFrame(c.fetchall()))
        x = c.fetchall()
        toc = time()
        print(toc - tic)
        t[i][2] = toc - tic
        connection.close()
        
        connection = mariadb.connect(user="user1", password= "password1", database = 'db4')
        c = connection.cursor()
        tic = time()
        c.execute(query)
        #print(pd.DataFrame(c.fetchall()))
        x = c.fetchall()
        toc = time()
        print(toc - tic)
        t[i][3] = toc - tic
        connection.close()
        
        connection = mariadb.connect(user="user1", password= "password1", database = 'db5')
        c = connection.cursor()
        tic = time()
        c.execute(query)
        #print(pd.DataFrame(c.fetchall()))
        x = c.fetchall()
        toc = time()
        print(toc - tic)
        t[i][4] = toc - tic
        connection.close()
        
        connection = mariadb.connect(user="user1", password= "password1", database = 'db6')
        c = connection.cursor()
        tic = time()
        c.execute(query)
        #print(pd.DataFrame(c.fetchall()))
        x = c.fetchall()
        toc = time()
        print(toc - tic)
        t[i][5] = toc - tic
        connection.close()
        
        connection = mariadb.connect(user="user1", password= "password1", database = 'db7')
        c = connection.cursor()
        tic = time()
        c.execute(query)
        #print(pd.DataFrame(c.fetchall()))
        x = c.fetchall()
        toc = time()
        print(toc - tic)
        t[i][6] = toc - tic
        connection.close()
        
        connection = mariadb.connect(user="user1", password= "password1", database = 'db8')
        c = connection.cursor()
        tic = time()
        c.execute(query)
        #print(pd.DataFrame(c.fetchall()))
        x = c.fetchall()
        toc = time()
        print(toc - tic)
        t[i][7] = toc - tic
        connection.close()
                
        connection = mariadb.connect(user="user1", password= "password1", database = 'db9')
        c = connection.cursor()
        tic = time()
        c.execute(query)
        #print(pd.DataFrame(c.fetchall()))
        x = c.fetchall()
        toc = time()
        print(toc - tic)
        t[i][8] = toc - tic
        connection.close()
        
    return t

### **Defining queries and time arrays**

In [15]:
query1 = 'SELECT * FROM A WHERE A1 <= 50'
query2 = 'SELECT * FROM B ORDER BY B3'
query3 = 'SELECT AVG(X.COL) FROM (SELECT COUNT(B2) AS COL FROM B GROUP BY B2) AS X'
query4 = 'SELECT A2, B1, B2, B3 FROM A, B WHERE A.A1 = B.B2'

In [16]:
time_q1 = [[0] * 9] * 7
time_q2 = [[0] * 9] * 7
time_q3 = [[0] * 9] * 7
time_q4 = [[0] * 9] * 7

### **Query 1 across all databases**

In [17]:
time_q1 = np.round(run_query(query1), 6)
print(time_q1)

     0     1
0    1   P-1
1    2   P-2
2    3   P-3
3    4   P-4
4    5   P-5
5    6   P-6
6    7   P-7
7    8   P-8
8    9   P-9
9   10  P-10
10  11  P-11
11  12  P-12
12  13  P-13
13  14  P-14
14  15  P-15
15  16  P-16
16  17  P-17
17  18  P-18
18  19  P-19
19  20  P-20
20  21  P-21
21  22  P-22
22  23  P-23
23  24  P-24
24  25  P-25
25  26  P-26
26  27  P-27
27  28  P-28
28  29  P-29
29  30  P-30
30  31  P-31
31  32  P-32
32  33  P-33
33  34  P-34
34  35  P-35
35  36  P-36
36  37  P-37
37  38  P-38
38  39  P-39
39  40  P-40
40  41  P-41
41  42  P-42
42  43  P-43
43  44  P-44
44  45  P-45
45  46  P-46
46  47  P-47
47  48  P-48
48  49  P-49
49  50  P-50
0.06991934776306152
     0     1
0    1   P-1
1    2   P-2
2    3   P-3
3    4   P-4
4    5   P-5
5    6   P-6
6    7   P-7
7    8   P-8
8    9   P-9
9   10  P-10
10  11  P-11
11  12  P-12
12  13  P-13
13  14  P-14
14  15  P-15
15  16  P-16
16  17  P-17
17  18  P-18
18  19  P-19
19  20  P-20
20  21  P-21
21  22  P-22
22  23  P-23
23  2

In [18]:
final_t1 = (np.sum(time_q1, axis = 0) - np.max(time_q1, axis = 0) - np.max(time_q1, axis = 0)) / 5
final_t1

array([0.002268, 0.002226, 0.002207, 0.003989, 0.003344, 0.002885,
       0.007639, 0.007895, 0.007029])

### **Query 2 across all databases**

In [19]:
time_q2 = np.round(run_query(query2), 6)
print(time_q2)

       0   1                  2
0    111  44           abhitsar
1    162  62           acApalya
2    100  38           adhyaMsa
3    156  60           aGgarAga
4     14   7        Ahirbudhnya
..   ...  ..                ...
261  147  56                zev
262  144  56       zmazAnavAsin
263   73  28        zRGgIkanaka
264  230  86      zumbhamardinI
265   54  22  zvetAzvatarazAkhA

[266 rows x 3 columns]
0.021118879318237305
       0   1               2
0    285  80          abhAna
1    259  75         abhidiz
2    228  67       abhiSyand
3    102  28   ADhakajambuka
4    156  45         adRpita
..   ...  ..             ...
353   53  15   zmazAnakAlikA
354  300  85     zuddhabodha
355  282  80    zuddhiviveka
356  162  46  zUramUrdhamaya
357  139  40      zvetadruma

[358 rows x 3 columns]
0.011845827102661133
       0   1                    2
0    167  31             abhijval
1    470  84              abhimuc
2    298  55           abhiprastR
3    225  42           abhisaMvRt
4    126

In [20]:
final_t2 = (np.sum(time_q2, axis = 0) - np.max(time_q2, axis = 0) - np.max(time_q2, axis = 0)) / 5
final_t2

array([2.7956000e-02, 3.2778000e-02, 1.1385000e-02, 4.1610000e-02,
       5.6506000e-02, 1.4690900e-01, 2.0387500e-01, 2.0765380e+00,
       1.8244629e+02])

### **Query 3 across all databases**

In [21]:
time_q3 = np.round(run_query(query3), 6)
print(time_q3)

        0
0  2.6600
0.41108059883117676
        0
0  3.5800
0.05562710762023926
        0
0  5.5600
0.04265451431274414
        0
0  3.4520
0.03376412391662598
        0
0  6.0940
0.05261850357055664
         0
0  25.4740
0.07149219512939453
        0
0  3.4910
0.07781171798706055
         0
0  26.0864
0.24269580841064453
          0
0  253.2790
1.6197445392608643
        0
0  2.6600
0.0017735958099365234
        0
0  3.5800
0.0019249916076660156
        0
0  5.5600
0.0026094913482666016
        0
0  3.4520
0.004515647888183594
        0
0  6.0940
0.006255626678466797
         0
0  25.4740
0.0197751522064209
        0
0  3.4910
0.031537532806396484
         0
0  26.0864
0.18848252296447754
          0
0  253.2790
1.6356351375579834
        0
0  2.6600
0.0017518997192382812
        0
0  3.5800
0.0019016265869140625
        0
0  5.5600
0.002012968063354492
        0
0  3.4520
0.0050013065338134766
        0
0  6.0940
0.0072095394134521484
         0
0  25.4740
0.020180940628051758
      

In [22]:
final_t3 = (np.sum(time_q3, axis = 0) - np.max(time_q3, axis = 0) - np.max(time_q3, axis = 0)) / 5
final_t3

array([0.002331, 0.001873, 0.002131, 0.004659, 0.006377, 0.021933,
       0.03442 , 0.178706, 1.539617])

### **Query 4 across all databases**

In [23]:
time_q4 = np.round(run_query(query4), 6)
print(time_q4)

         0    1    2               3
0      P-1    1    1       meghavana
1      P-1    2    1             guh
2      P-1    3    1        mAMsepad
3      P-2    4    2    uttarapurANa
4      P-3    5    3     uttamarNika
..     ...  ...  ...             ...
261   P-99  262   99  narapativijaya
262   P-99  263   99          baraTa
263   P-99  264   99         niriGga
264  P-100  265  100           mabhr
265  P-100  266  100         drimila

[266 rows x 4 columns]
0.19121122360229492
         0    1    2            3
0      P-1    1    1       lAlATi
1      P-1    2    1   rAmayantra
2      P-1    3    1  rAtraubhava
3      P-1    4    1  vidyunmukha
4      P-2    5    2     gharaTTa
..     ...  ...  ...          ...
353  P-100  354  100       lakSyI
354  P-100  355  100     mAtAmahI
355  P-100  356  100    devajuSTa
356  P-100  357  100      govAhin
357  P-100  358  100   mukhazRGga

[358 rows x 4 columns]
1.2877171039581299
         0    1    2              3
0      P-1    1    1     

In [24]:
final_t4 = (np.sum(time_q4, axis = 0) - np.max(time_q4, axis = 0) - np.max(time_q4, axis = 0)) / 5
final_t4

array([1.09830000e-02, 1.22730000e-02, 1.58510000e-02, 5.09343000e-01,
       8.69416000e-01, 3.65175900e+00, 4.88013940e+01, 3.61422220e+02,
       3.55011465e+03])

In [25]:
print(time_q1)
print(time_q2)
print(time_q3)
print(time_q4)

[[0.002268 0.002226 0.002207 0.003989 0.003344 0.002885 0.007639 0.007895
  0.007029]
 [0.002268 0.002226 0.002207 0.003989 0.003344 0.002885 0.007639 0.007895
  0.007029]
 [0.002268 0.002226 0.002207 0.003989 0.003344 0.002885 0.007639 0.007895
  0.007029]
 [0.002268 0.002226 0.002207 0.003989 0.003344 0.002885 0.007639 0.007895
  0.007029]
 [0.002268 0.002226 0.002207 0.003989 0.003344 0.002885 0.007639 0.007895
  0.007029]
 [0.002268 0.002226 0.002207 0.003989 0.003344 0.002885 0.007639 0.007895
  0.007029]
 [0.002268 0.002226 0.002207 0.003989 0.003344 0.002885 0.007639 0.007895
  0.007029]]
[[2.7956000e-02 3.2778000e-02 1.1385000e-02 4.1610000e-02 5.6506000e-02
  1.4690900e-01 2.0387500e-01 2.0765380e+00 1.8244629e+02]
 [2.7956000e-02 3.2778000e-02 1.1385000e-02 4.1610000e-02 5.6506000e-02
  1.4690900e-01 2.0387500e-01 2.0765380e+00 1.8244629e+02]
 [2.7956000e-02 3.2778000e-02 1.1385000e-02 4.1610000e-02 5.6506000e-02
  1.4690900e-01 2.0387500e-01 2.0765380e+00 1.8244629e+02]
 [2.

### **Saving times collected to csv**

In [26]:
import csv
with open("t1.csv", "w+") as my_csv:
    writer = csv.writer(my_csv, delimiter=',')
    writer.writerows(time_q1)

In [27]:
with open("t2.csv", "w+") as my_csv:
    writer = csv.writer(my_csv, delimiter=',')
    writer.writerows(time_q2)

In [28]:
with open("t3.csv", "w+") as my_csv:
    writer = csv.writer(my_csv, delimiter=',')
    writer.writerows(time_q3)

In [29]:
with open("t4.csv", "w+") as my_csv:
    writer = csv.writer(my_csv, delimiter=',')
    writer.writerows(time_q4)